eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: member
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.93.132:3306/sc-book?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
